export const categories = {
  Bikes: [
    'Scooters',
    'Bicycles',
    'Motorcycles',
    'Spare Parts',
    'ATV & Quads',
    'Bikes Accessories',
  ],
  Jobs: [
    'Sales',
    'Medical',
    'Online',
    'Marketing',
    'Education',
    'Security',
    'Part Time',
    'Engineering',
    'Internships',
    'Other Jobs',
    'Content Writing',
    'Graphic Design',
    'IT & Networking',
    'Delivery Riders',
    'Domestic Staff',
    'Customer Service',
    'Human Resources',
    'Manufacturing',
    'Hotels & Tourism',
    'Real Estate',
    'Accounting & Finance',
    'Advertising & PR',
    'Clerical & Administration',
    'Restaurants & Hospitality',
    'Architecture & Interior Design',
  ],
  Kids: [
    'Toys',
    'Baby Gear',
    'Kids Vehicles',
    'Kids Clothing',
    'Kids Furniture',
    'Bath & Diapers',
    'Swings & Slides',
    'Kids Accessories',
  ],
  Animals: [
    'Cats',
    'Dogs',
    'Ducks',
    'Fish',
    'Hens',
    'Doves',
    'Rabbits',
    'Horses',
    'Pigeons',
    'Finches',
    'Parrots',
    'Peacocks',
    'Livestock',
    'Other Birds',
    'Fertile Eggs',
    'Other Animals',
    'Pet Food & Accessories',
  ],
  Property: [
    'Rooms',
    'Houses',
    'Land & Plots',
    'Apartments & Flats',
    'Portions & Floors',
    'Roommates & Paying Guests',
    'Vacation Rentals - Guest Houses',
    'Shops - Offices - Commercial Space',
  ],
  Services: [
    'Car Rental',
    'Web Development',
    'Travel & Visa',
    'Event Services',
    'Domestic Help',
    'Drivers & Taxi',
    'Other Services',
    'Tuitions & Academies',
    'Movers & Packers',
    'Renting Services',
    'Car Services',
    'Tailor Services',
    'Insurance Services',
    'Home & Office Repair',
    'Construction Services',
    'Consultancy Services',
    'Farm & Fresh Food',
    'Health & Beauty',
    'Video & Photography',
    'Camera Installation',
    'Catering & Restaurant',
    'Electronics & Computer Repair',
    'Architecture & Interior Design',
  ],
  Vehicles: [
    'Cars',
    'Boats',
    'Spare Parts',
    'Cars Accessories',
    'Other Vehicles',
    'Motorcycles',
    'Cars on Installments',
    'Buses, Vans & Trucks',
    'Rickshaw & Chingchi',
    'Tractors & Trailers',
  ],
  'Mobile Phones': ['Tablets', 'Accessories', 'Mobile Phones', 'Smart Watches'],
  'Fashion & Beauty': [
    'Bags',
    'Clothes',
    'Watches',
    'Wedding',
    'Footwear',
    'Jewellery',
    'Fragrance',
    'Makeup',
    'Skin & Hair',
    'Other Fashion',
    'Fashion Accessories',
  ],
  'Furniture & Home Decor': [
    'Beds & Wardrobes',
    'Sofa & Chairs',
    'Tables & Dining',
    'Garden & Outdoor',
    'Home Decoration',
    'Office Furniture',
    'Rugs & Carpets',
    'Bathroom Accessories',
    'Curtains & Blinds',
    'Painting & Mirrors',
    'Other Household Items',
  ],
  'Books, Sports & Hobbies': [
    'Gym & Fitness',
    'Other Hobbies',
    'Sports Equipment',
    'Musical Instruments',
    'Books & Magazines',
  ],
  'Electronics & Home Appliances': [
    'Fans',
    'Video-Audios',
    'Kitchen Appliances',
    'Cameras & Accessories',
    'Games & Entertainment',
    'Heaters & Geysers',
    'AC & Coolers',
    'Sewing Machines',
    'Washing Machines & Dryers',
    'Refrigerators & Freezers',
    'Microwaves & Ovens',
    'Irons & Steamers',
    'Water Dispensers',
    'Other Home Appliances',
    'Computers & Accessories',
    'Televisions & Accessories',
    'Air Purifiers & Humidifiers',
    'Generators, UPS & Power Solutions',
  ],
  'Business, Industrial & Agriculture': [
    'Agriculture',
    'Business for Sale',
    'Food & Restaurants',
    'Medical & Pharma',
    'Other Business & Industry',
    'Construction & Heavy Machinery',
    'Trade & Industrial Machinery',
  ],
};
