export const mobiles = [
  {
    id: 1,
    name: 'iPhone 13 Pro',
    brand: 'Apple',
    price: 70000,
    currency: 'PKR',
    images: ['/iphone.jpg'],
    specs: {
      screen_size: '6.1 inches',
      battery: '3095 mAh',
      camera: '12 MP',
      storage: '128 GB',
      ram: '6 GB',
    },
    availability: true,
    colors: ['Graphite', 'Silver', 'Gold', 'Sierra Blue'],
    address: {
      street: '123 Main Street',
      city: 'Lahore',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '54000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
  },
  {
    id: 2,
    name: 'Samsung Galaxy S21 Ultra',
    brand: 'Samsung',
    price: 119900,
    currency: 'PKR',
    images: ['/samsung.jpeg'],
    specs: {
      screen_size: '6.8 inches',
      battery: '5000 mAh',
      camera: '108 MP',
      storage: '256 GB',
      ram: '12 GB',
    },
    availability: true,
    colors: ['Phantom Black', 'Phantom Silver', 'Navy'],
    address: {
      street: '456 Market Road',
      city: 'Karachi',
      state: 'Sindh',
      country: 'Pakistan',
      postalCode: '74000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
  },
  {
    id: 3,
    name: 'Google Pixel 9',
    brand: 'Google',
    price: 120000,
    currency: 'PKR',
    images: ['/google.jpg'],
    specs: {
      screen_size: '6.3 inches',
      battery: '4355 mAh',
      camera: '50 MP',
      storage: '128 GB',
      ram: '8 GB',
    },
    availability: false,
    colors: ['Obsidian', 'Lemongrass', 'Snow'],
    address: {
      street: '789 Tech Avenue',
      city: 'Islamabad',
      state: 'ICT',
      country: 'Pakistan',
      postalCode: '44000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
  },
  {
    id: 4,
    name: 'OnePlus 13',
    brand: 'OnePlus',
    price: 90000,
    currency: 'PKR',
    images: ['/onePlus.jpg'],
    specs: {
      screen_size: '6.7 inches',
      battery: '5000 mAh',
      camera: '50 MP',
      storage: '256 GB',
      ram: '12 GB',
    },
    availability: true,
    colors: ['Titan Black', 'Eternal Green'],
    address: {
      street: '101 Infinity Plaza',
      city: 'Faisalabad',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '38000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
  },
];

export const cars = [
  {
    id: 1,
    name: 'Toyota Aqua',
    brand: 'Toyota',
    price: 3500000,
    currency: 'PKR',
    images: ['/cars/aqua.jpg'],
    specs: {
      engine: '1.5L',
      fuel_type: 'Hybrid',
      transmission: 'Automatic',
      seats: '5',
      mileage: '25 km/l',
    },
    availability: true,
    colors: ['White', 'Silver', 'Blue', 'Black'],
    address: {
      street: '123 Main Street',
      city: 'Lahore',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '54000',
    },
    createdAt: '2025-01-09T03:00:26.000Z',
  },
  {
    id: 2,
    name: 'Toyota Corolla',
    brand: 'Toyota',
    price: 5500000,
    currency: 'PKR',
    images: ['/cars/corolla.jpeg'],
    specs: {
      engine: '1.8L',
      fuel_type: 'Petrol',
      transmission: 'Automatic',
      seats: '5',
      mileage: '14 km/l',
    },
    availability: true,
    colors: ['White', 'Silver', 'Black', 'Grey'],
    address: {
      street: '456 Market Road',
      city: 'Karachi',
      state: 'Sindh',
      country: 'Pakistan',
      postalCode: '74000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
  },
  {
    id: 3,
    name: 'Suzuki Cultus',
    brand: 'Suzuki',
    price: 2500000,
    currency: 'PKR',
    images: ['/cars/cultus.jpg'],
    specs: {
      engine: '1.0L',
      fuel_type: 'Petrol',
      transmission: 'Manual',
      seats: '5',
      mileage: '18 km/l',
    },
    availability: false,
    colors: ['White', 'Silver', 'Red', 'Blue'],
    address: {
      street: '789 Tech Avenue',
      city: 'Islamabad',
      state: 'ICT',
      country: 'Pakistan',
      postalCode: '44000',
    },
    createdAt: '2025-01-09T02:20:26.000Z',
  },
  {
    id: 4,
    name: 'Toyota Yaris',
    brand: 'Toyota',
    price: 4000000,
    currency: 'PKR',
    images: ['/cars/yaris.jpg'],
    specs: {
      engine: '1.5L',
      fuel_type: 'Petrol',
      transmission: 'Automatic',
      seats: '5',
      mileage: '16 km/l',
    },
    availability: true,
    colors: ['White', 'Silver', 'Red', 'Black'],
    address: {
      street: '101 Infinity Plaza',
      city: 'Faisalabad',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '38000',
    },
    createdAt: '2025-01-09T03:00:26.000Z',
  },
];
