import { Chat } from './definitions';

export const mobiles = [
  {
    id: 1,
    name: 'iPhone 13 Pro',
    brand: 'Apple',
    price: 70000,
    currency: 'PKR',
    image1: '/iphone.jpg',
    specs: {
      screen_size: '6.1 inches',
      battery: '3095 mAh',
      camera: '12 MP',
      storage: '128 GB',
      ram: '6 GB',
    },
    category: ['mobilePhones'],
    availability: true,
    colors: ['Graphite', 'Silver', 'Gold', 'Sierra Blue'],
    address: {
      street: '123 Main Street',
      city: 'Lahore',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '54000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
    keywords: [
      'iphone',
      'apple',
      'mobile',
      'smartphone',
      'ios',
      'mobilePhones',
    ],
  },
  {
    id: 2,
    name: 'Samsung Galaxy S21 Ultra',
    brand: 'Samsung',
    price: 119900,
    currency: 'PKR',
    image1: '/samsung.jpeg',
    specs: {
      screen_size: '6.8 inches',
      battery: '5000 mAh',
      camera: '108 MP',
      storage: '256 GB',
      ram: '12 GB',
    },
    category: ['mobilePhones'],
    availability: true,
    colors: ['Phantom Black', 'Phantom Silver', 'Navy'],
    address: {
      street: '456 Market Road',
      city: 'Karachi',
      state: 'Sindh',
      country: 'Pakistan',
      postalCode: '74000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
    keywords: [
      'android',
      'phone',
      'samsung',
      'mobile',
      'smartphone',
      'mobilePhones',
    ],
  },
  {
    id: 3,
    name: 'Google Pixel 9',
    brand: 'Google',
    price: 120000,
    currency: 'PKR',
    image1: '/google.jpg',
    specs: {
      screen_size: '6.3 inches',
      battery: '4355 mAh',
      camera: '50 MP',
      storage: '128 GB',
      ram: '8 GB',
    },
    category: ['mobilePhones'],
    availability: false,
    colors: ['Obsidian', 'Lemongrass', 'Snow'],
    address: {
      street: '789 Tech Avenue',
      city: 'Islamabad',
      state: 'ICT',
      country: 'Pakistan',
      postalCode: '44000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
    keywords: [
      'google',
      'pixel',
      'android',
      'mobile',
      'smartphone',
      'mobilePhones',
    ],
  },
  {
    id: 4,
    name: 'OnePlus 13',
    brand: 'OnePlus',
    price: 90000,
    currency: 'PKR',
    image1: '/onePlus.jpg',
    specs: {
      screen_size: '6.7 inches',
      battery: '5000 mAh',
      camera: '50 MP',
      storage: '256 GB',
      ram: '12 GB',
    },
    category: ['mobilePhones'],
    availability: true,
    colors: ['Titan Black', 'Eternal Green'],
    address: {
      street: '101 Infinity Plaza',
      city: 'Faisalabad',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '38000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
    keywords: ['oneplus', 'android', 'mobile', 'smartphone', 'mobilePhones'],
  },
];

export const cars = [
  {
    id: 5,
    name: 'Toyota Aqua',
    brand: 'Toyota',
    price: 3500000,
    currency: 'PKR',
    image1: '/cars/aqua.jpg',
    specs: {
      engine: '1.5L',
      fuel_type: 'Hybrid',
      transmission: 'Automatic',
      seats: '5',
      mileage: '25 km/l',
    },
    category: ['cars', 'vehicles'],
    availability: true,
    colors: ['White', 'Silver', 'Blue', 'Black'],
    address: {
      street: '123 Main Street',
      city: 'Lahore',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '54000',
    },
    createdAt: '2025-01-09T03:00:26.000Z',
    keywords: ['toyota', 'aqua', 'car', 'hybrid', 'cars', 'vehicles'],
  },
  {
    id: 6,
    name: 'Toyota Corolla',
    brand: 'Toyota',
    price: 5500000,
    currency: 'PKR',
    image1: '/cars/corolla.jpeg',
    specs: {
      engine: '1.8L',
      fuel_type: 'Petrol',
      transmission: 'Automatic',
      seats: '5',
      mileage: '14 km/l',
    },
    category: ['cars', 'vehicles'],
    availability: true,
    colors: ['White', 'Silver', 'Black', 'Grey'],
    address: {
      street: '456 Market Road',
      city: 'Karachi',
      state: 'Sindh',
      country: 'Pakistan',
      postalCode: '74000',
    },
    createdAt: '2025-01-09T01:00:26.000Z',
    keywords: ['toyota', 'corolla', 'car', 'sedan', 'cars', 'vehicles'],
  },
  {
    id: 7,
    name: 'Suzuki Cultus',
    brand: 'Suzuki',
    price: 2500000,
    currency: 'PKR',
    image1: '/cars/cultus.jpg',
    specs: {
      engine: '1.0L',
      fuel_type: 'Petrol',
      transmission: 'Manual',
      seats: '5',
      mileage: '18 km/l',
    },
    category: ['cars', 'vehicles'],
    availability: false,
    colors: ['White', 'Silver', 'Red', 'Blue'],
    address: {
      street: '789 Tech Avenue',
      city: 'Islamabad',
      state: 'ICT',
      country: 'Pakistan',
      postalCode: '44000',
    },
    createdAt: '2025-01-09T02:20:26.000Z',
    keywords: ['suzuki', 'cultus', 'car', 'compact', 'cars', 'vehicles'],
  },
  {
    id: 8,
    name: 'Toyota Yaris',
    brand: 'Toyota',
    price: 4000000,
    currency: 'PKR',
    image1: '/cars/yaris.jpg',
    specs: {
      engine: '1.5L',
      fuel_type: 'Petrol',
      transmission: 'Automatic',
      seats: '5',
      mileage: '16 km/l',
    },
    category: ['cars', 'vehicles'],
    availability: true,
    colors: ['White', 'Silver', 'Red', 'Black'],
    address: {
      street: '101 Infinity Plaza',
      city: 'Faisalabad',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '38000',
    },
    createdAt: '2025-01-09T03:00:26.000Z',
    keywords: [
      'toyota',
      'yaris',
      'car',
      'compact',
      'sedan',
      'cars',
      'vehicles',
    ],
  },
];

export const property = [
  {
    id: 9,
    name: '1125 Square Feet Residential Plot In Wapda Town - Block A For Sale',
    brand: '',
    price: 25000000,
    currency: 'PKR',
    image1: '/property/property01.webp',
    category: ['property'],
    address: {
      street: '789 Tech Avenue',
      city: 'Islamabad',
      state: 'ICT',
      country: 'Pakistan',
      postalCode: '44000',
    },
    createdAt: '2025-01-09T02:20:26.000Z',
    keywords: ['plot', 'residential', 'property', 'real estate', 'property'],
  },
  {
    id: 10,
    name: '1 Kanal Luxurious House in DHA Phase 6 - For Sale',
    brand: 'DHA Builders',
    price: 85000000,
    currency: 'PKR',
    image1: '/property/property02.webp',
    category: ['Houses', 'property'],
    address: {
      street: '123 Elite Lane',
      city: 'Lahore',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '54000',
    },
    createdAt: '2025-01-10T14:45:00.000Z',
    keywords: ['luxury', 'house', 'property', 'real estate', 'Houses'],
  },
  {
    id: 11,
    name: '5 Marla Double Storey House in Bahria Town - For Sale',
    brand: 'Bahria Developers',
    price: 15000000,
    currency: 'PKR',
    image1: '/property/property03.webp',
    category: ['Houses', 'property'],
    address: {
      street: '456 Bahria Main Boulevard',
      city: 'Karachi',
      state: 'Sindh',
      country: 'Pakistan',
      postalCode: '75500',
    },
    createdAt: '2025-01-10T16:10:00.000Z',
    keywords: ['house', 'double storey', 'real estate', 'Houses'],
  },
  {
    id: 12,
    name: '10 Marla Commercial Plot in Blue World City - For Sale',
    brand: '',
    price: 40000000,
    currency: 'PKR',
    image1: '/property/property04.webp',
    category: ['property'],
    address: {
      street: '101 Blue Boulevard',
      city: 'Rawalpindi',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '46000',
    },
    createdAt: '2025-01-11T09:30:00.000Z',
    keywords: [
      'commercial plot',
      'real estate',
      'property',
      'investment',
      'property',
    ],
  },
];

export const bikes = [
  {
    id: 13,
    name: 'Honda CG 125 - 2023 Model',
    brand: 'Honda',
    price: 185000,
    currency: 'PKR',
    image1: '/bikes/bike-1.webp',
    specifications: {
      engine: '125cc',
      mileage: '45 km/l',
      transmission: '4-speed',
      color: 'Red',
    },
    category: ['Motorcycles', 'bikes'],
    address: {
      street: '45 Auto Market Road',
      city: 'Lahore',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '54000',
    },
    createdAt: '2025-01-10T05:15:00.000Z',
    keywords: ['honda', 'cg125', 'motorcycle', 'bike', 'Honda Motorcycles'],
  },
  {
    id: 14,
    name: 'Yamaha YBR 125 - 2023 Model',
    brand: 'Yamaha',
    price: 275000,
    currency: 'PKR',
    image1: '/bikes/bike-2.jpeg',
    specifications: {
      engine: '125cc',
      mileage: '50 km/l',
      transmission: '5-speed',
      color: 'Black',
    },
    category: ['Motorcycles', 'bikes'],
    address: {
      street: '67 Bike Street',
      city: 'Karachi',
      state: 'Sindh',
      country: 'Pakistan',
      postalCode: '74000',
    },
    createdAt: '2025-01-10T07:45:00.000Z',
    keywords: ['yamaha', 'ybr125', 'motorcycle', 'bike', 'Yamaha Motorcycles'],
  },
  {
    id: 15,
    name: 'Suzuki GS 150 SE - 2023 Model',
    brand: 'Suzuki',
    price: 250000,
    currency: 'PKR',
    image1: '/bikes/bike-3.webp',
    specifications: {
      engine: '150cc',
      mileage: '40 km/l',
      transmission: '5-speed',
      color: 'Blue',
    },
    category: ['Motorcycles', 'bikes'],
    address: {
      street: '123 Bike Plaza',
      city: 'Islamabad',
      state: 'ICT',
      country: 'Pakistan',
      postalCode: '44000',
    },
    createdAt: '2025-01-10T09:30:00.000Z',
    keywords: ['suzuki', 'gs150', 'motorcycle', 'bike', 'Suzuki Motorcycles'],
  },
  {
    id: 16,
    name: 'Kawasaki Ninja 400 - 2023 Model',
    brand: 'Kawasaki',
    price: 1200000,
    currency: 'PKR',
    image1: '/bikes/bike-4.webp',
    specifications: {
      engine: '399cc',
      mileage: '25 km/l',
      transmission: '6-speed',
      color: 'Green',
    },
    category: ['Motorcycles', 'bikes'],
    address: {
      street: '89 Race Track Lane',
      city: 'Rawalpindi',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '46000',
    },
    createdAt: '2025-01-10T11:00:00.000Z',
    keywords: [
      'kawasaki',
      'ninja400',
      'motorcycle',
      'sports bike',
      'Kawasaki Motorcycles',
    ],
  },
];

export const jobs = [
  {
    id: 17,
    title: 'Software Engineer',
    company: 'Tech Solutions Pvt. Ltd.',
    address: {
      street: '1 Innovation Drive',
      city: 'Lahore',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '54000',
    },
    salary: 'PKR 120,000 - 150,000',
    type: 'Full-time',
    image1: '',
    description:
      'We are looking for a skilled Software Engineer to join our team and develop scalable web applications.',
    requirements: [
      "Bachelor's degree in Computer Science",
      '2+ years of experience in software development',
      'Proficiency in JavaScript, React, and Node.js',
    ],
    createdAt: '2025-01-10T10:00:00.000Z',
    category: ['jobs', 'IT & Software'],
    keywords: [
      'software engineer',
      'developer',
      'programming',
      'tech',
      'job',
      'IT',
      'web development',
    ],
  },
  {
    id: 18,
    title: 'Graphic Designer',
    company: 'Creative Minds Studio',
    address: {
      street: '55 Art Street',
      city: 'Karachi',
      state: 'Sindh',
      country: 'Pakistan',
      postalCode: '75500',
    },
    salary: 'PKR 50,000 - 70,000',
    type: 'Part-time',
    image1: '',
    description:
      'Seeking a creative Graphic Designer to produce engaging visual content for our marketing campaigns.',
    requirements: [
      'Proficiency in Adobe Creative Suite (Photoshop, Illustrator)',
      'Strong portfolio of design work',
      'Ability to meet deadlines',
    ],
    createdAt: '2025-01-09T14:30:00.000Z',
    category: ['jobs', 'Design & Creative'],
    keywords: [
      'graphic designer',
      'design',
      'creative',
      'art',
      'Adobe',
      'job',
      'marketing',
    ],
  },
  {
    id: 19,
    title: 'Digital Marketing Specialist',
    company: 'BizGrowth Agency',
    address: {
      street: '10 Growth Avenue',
      city: 'Islamabad',
      state: 'ICT',
      country: 'Pakistan',
      postalCode: '44000',
    },
    salary: 'PKR 80,000 - 100,000',
    type: 'Contract',
    image1: '',
    description:
      'Hiring a Digital Marketing Specialist to manage social media campaigns and analyze performance metrics.',
    requirements: [
      '3+ years of experience in digital marketing',
      'Expertise in SEO, SEM, and social media management',
      'Strong analytical skills',
    ],
    createdAt: '2025-01-08T09:45:00.000Z',
    category: ['jobs', 'Marketing & Sales'],
    keywords: [
      'digital marketing',
      'SEO',
      'SEM',
      'social media',
      'marketing',
      'analytics',
      'job',
    ],
  },
  {
    id: 20,
    title: 'Customer Support Representative',
    company: 'Global Solutions Ltd.',
    address: {
      street: '23 Service Lane',
      city: 'Rawalpindi',
      state: 'Punjab',
      country: 'Pakistan',
      postalCode: '46000',
    },
    salary: 'PKR 40,000 - 50,000',
    type: 'Full-time',
    image1: '',
    description:
      'We need a friendly and detail-oriented Customer Support Representative to assist our clients with their queries.',
    requirements: [
      'Excellent communication skills',
      'Experience in customer service or a related field',
      'Proficiency in MS Office and CRM software',
    ],
    createdAt: '2025-01-11T12:00:00.000Z',
    category: ['jobs', 'Customer Service'],
    keywords: [
      'customer support',
      'representative',
      'service',
      'communication',
      'job',
      'CRM',
      'MS Office',
    ],
  },
];

export const allItems = [...mobiles, ...cars, ...property, ...bikes];

export const chats: Chat[] = [
  {
    chat_id: 'Alice_101',
    chat_name: 'Alice',
    messages: [
      {
        message_id: 'msg_1',
        chat_id: 'Alice_101',
        sender_id: '1',
        body: 'Hey, how are you?',
        created_at: '2023-01-01T12:00:00.000Z',
      },
      {
        message_id: 'msg_2',
        chat_id: 'Alice_101',
        sender_id: '2',
        body: 'I am good, thanks! What about you?',
        created_at: '2023-01-01T13:30:00.000Z',
      },
    ],
  },
  { chat_id: 'Bob_102', chat_name: 'Bob' },
  { chat_id: 'Charlie_103', chat_name: 'Charlie' },
  { chat_id: 'David_104', chat_name: 'David' },
  {
    chat_id: 'Eve_105',
    chat_name: 'Eve',
    messages: [
      {
        message_id: 'msg_3',
        chat_id: 'Eve_105',
        sender_id: '1',
        body: 'Hey Eve, are you free to talk?',
        created_at: '2023-01-01T15:00:00.000Z',
      },
    ],
  },
];
